### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ricardosohn** [rsxdalv/albion-trader#1]
Hello, I've tried to use the tool, but it did not work for me.
The console appears, then it opens the web page, but ift does not recognize anything from my client.
I tried running the program as administrator but it did not work as well.
Any ideas?

**Comment by ricardosohn** [comment]
Im running on a windows 10 64 bit machine.

**Comment by rsxdalv** [comment]
Hi, @ricardosohn!

I'll make a tutorial video later today detailing the working use case & installation, so that we can see if the issues arise there.

One idea I have is that since I'm getting 99% trading messages, another type of message that I haven't tested for is messing it up. Do you have any messages in your last 50 (visible window) that are not market notifications?

**Comment by ricardosohn** [comment]
I have some, but they were not showing on the 1st page the time I was testing. I had like 300+ market notifications.

**Comment by rsxdalv** [comment]
I imagine there's no output in the console, right?

**Comment by ricardosohn** [comment]
Exactly, no output.
Also, what are the steps to run the source code locally? 
I cloned the repo and tried the usual npm install / npm start.
Did not work as well.

**Comment by rsxdalv** [comment]
You start it by node ./albion-history.js, it'll error about not having a database file, but I think it just creates it, so no issue there.

**Comment by ricardosohn** [comment]
Run files in windows cmd like that? It does not work for me.

By the way, in ```albion-history.js``` there is this line:

```var device = Cap.findDevice('192.168.0.100');```

This is probably the cause of the issue on the packaged version. 
This is a local IP and can be different according to your network settings.
Since it's hardcoded, it will not work if the person using have different local network settings.
For example, for me right now it's ```192.168.1.3```.

If you'd like, you can contact me in discord at ```rDs#7008```, so we can figure out what's happening faster and then I can start contributing with this.

**Comment by rsxdalv** [comment]
Ok, I guess I made something that works only on network cards such as mine lol, sorry. 
Let's get it running for you first and then I'll work out the patch, I know what to do.

Edit: as for the command, yes, it should be that after a (successful) npm install you just `node ./albion-history.js` given that you have node installed (it shouldn't be too picky on node versions, so I'll assume 6 and up works).
